In [1]:
### Importing Libraries
import tensorflow as tf
import keras
#### one_hot libray converts words in sentence to some specific index
from tensorflow.keras.preprocessing.text import one_hot

In [2]:
#### we provide sentence
sent=['the glass of milk',
      'i am good boy',
      'the glass of juice',
      'the cup of tea',
      'I am good developer',
      'understand meaning of words',
      'your ideos are good',
      'its her choice',]

In [3]:
sent

['the glass of milk',
 'i am good boy',
 'the glass of juice',
 'the cup of tea',
 'I am good developer',
 'understand meaning of words',
 'your ideos are good',
 'its her choice']

In [4]:
#### if we give this size the index of words will be between 0 to vocab size
### Vocabulory Size provided
vocab_size=10000

In [5]:
#### one_hot library used
onehot_repr=[one_hot(words,vocab_size)for words in sent]

In [6]:
onehot_repr

[[6570, 5005, 4701, 4954],
 [9923, 2974, 3433, 9594],
 [6570, 5005, 4701, 6888],
 [6570, 3347, 4701, 7693],
 [9923, 2974, 3433, 2776],
 [5348, 1638, 4701, 8142],
 [1312, 4161, 7053, 3433],
 [3943, 7666, 157]]

# **Word Embedding Representation**

In [7]:
##### Importing Libraries
from tensorflow.keras.layers import Embedding
from tensorflow.keras.models import Sequential #### for model
from tensorflow.keras.preprocessing.sequence import pad_sequences

In [8]:
import numpy as np


In [9]:
#### pad sequence library used
sent_length=8 ### by these number we get array of 8 rows. it starts filling from back side. remaining columns will fill with 0
embedded_docs=pad_sequences(sequences=onehot_repr,padding='pre',maxlen=sent_length)

In [10]:
embedded_docs

array([[   0,    0,    0,    0, 6570, 5005, 4701, 4954],
       [   0,    0,    0,    0, 9923, 2974, 3433, 9594],
       [   0,    0,    0,    0, 6570, 5005, 4701, 6888],
       [   0,    0,    0,    0, 6570, 3347, 4701, 7693],
       [   0,    0,    0,    0, 9923, 2974, 3433, 2776],
       [   0,    0,    0,    0, 5348, 1638, 4701, 8142],
       [   0,    0,    0,    0, 1312, 4161, 7053, 3433],
       [   0,    0,    0,    0,    0, 3943, 7666,  157]], dtype=int32)

In [11]:
### features for embedding layer
dim=10

In [12]:
model=Sequential()

In [13]:
#### Embedding Layer starts
model.add(Embedding(vocab_size,dim,input_length=sent_length))


In [14]:
### Compiling model with Adam optimizer and accuracy is mean-squared-error
model.compile('adam','mse')

In [15]:
model.summary()

Model: "sequential"
_________________________________________________________________
Layer (type)                 Output Shape              Param #   
embedding (Embedding)        (None, 8, 10)             100000    
Total params: 100,000
Trainable params: 100,000
Non-trainable params: 0
_________________________________________________________________


In [16]:
### prediction of model
model.predict(embedded_docs)

array([[[ 0.04876446,  0.01298672,  0.04766282, -0.04552174,
         -0.01878211,  0.01633172, -0.02232053,  0.01341411,
         -0.00055934,  0.01888093],
        [ 0.04876446,  0.01298672,  0.04766282, -0.04552174,
         -0.01878211,  0.01633172, -0.02232053,  0.01341411,
         -0.00055934,  0.01888093],
        [ 0.04876446,  0.01298672,  0.04766282, -0.04552174,
         -0.01878211,  0.01633172, -0.02232053,  0.01341411,
         -0.00055934,  0.01888093],
        [ 0.04876446,  0.01298672,  0.04766282, -0.04552174,
         -0.01878211,  0.01633172, -0.02232053,  0.01341411,
         -0.00055934,  0.01888093],
        [-0.03375135, -0.04985218, -0.04977154, -0.02680398,
         -0.02688911, -0.04294559,  0.03030663,  0.02245362,
         -0.04041771, -0.00140373],
        [-0.02760425,  0.00847805, -0.01466708,  0.02995551,
          0.02169969, -0.00454111, -0.01875519, -0.01189692,
          0.0182634 , -0.01007931],
        [ 0.045333  ,  0.00478875, -0.03064052, -0.0

In [17]:
### first sentence
embedded_docs[0]

array([   0,    0,    0,    0, 6570, 5005, 4701, 4954], dtype=int32)

In [18]:
model.predict(embedded_docs[0]) #### its giving 10 values for each embedded_docs[i] value

array([[[ 0.04876446,  0.01298672,  0.04766282, -0.04552174,
         -0.01878211,  0.01633172, -0.02232053,  0.01341411,
         -0.00055934,  0.01888093]],

       [[ 0.04876446,  0.01298672,  0.04766282, -0.04552174,
         -0.01878211,  0.01633172, -0.02232053,  0.01341411,
         -0.00055934,  0.01888093]],

       [[ 0.04876446,  0.01298672,  0.04766282, -0.04552174,
         -0.01878211,  0.01633172, -0.02232053,  0.01341411,
         -0.00055934,  0.01888093]],

       [[ 0.04876446,  0.01298672,  0.04766282, -0.04552174,
         -0.01878211,  0.01633172, -0.02232053,  0.01341411,
         -0.00055934,  0.01888093]],

       [[-0.03375135, -0.04985218, -0.04977154, -0.02680398,
         -0.02688911, -0.04294559,  0.03030663,  0.02245362,
         -0.04041771, -0.00140373]],

       [[-0.02760425,  0.00847805, -0.01466708,  0.02995551,
          0.02169969, -0.00454111, -0.01875519, -0.01189692,
          0.0182634 , -0.01007931]],

       [[ 0.045333  ,  0.00478875, -0.03